domains:
- domain: alexeevivan.com
  type: PRIMARY
  zone: alexeevivan.com
name: portfolio-app
region: fra
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: alexeevivan/Portfolio
  name: portfolio
  routes:
  - path: /
  source_dir: /project/build/
